# Generated by Django 3.2.24 on 2024-05-24 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_rates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(default='0', max_length=11),
        ),
        migrations.AddField(
            model_name='hotel',
            name='policies',
            field=models.CharField(default='Our Policies', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='brochure',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.city'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
