# Generated by Django 5.0.3 on 2024-04-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='number_of_rates',
            field=models.IntegerField(default=0),
        ),
    ]
