name: Django CI

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install django
        pip install PyYAML
    - name: Run Tests
      run: |
        source venv/bin/activate
        cd django/pythonProject/BookHotel
        python manage.py test
