name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Django
        run: |
          python -m pip install --upgrade pip
          pip install django

      - name: Run tests
        run: |
          python django/pythonProject/BookHotel/manage.py test
